### ISSUE TITLE
libc++abi.dylib: terminating with uncaught exception of type libipatcher::exception: std::exception

### ISSUE THREAD

**Issue by arinc9** [tihmstar/libipatcher#9]
Arncs-iMac:futurerestore-latest arinc$ ./futurerestore_macos --use-pwndfu --no-baseband -t /Users/arinc/Desktop/odysseusOTA2/macos/shsh/612068262897-iPad2,5-8.4.1.shsh /Users/arinc/Desktop/iPad2,5_8.4.1_12H321_Restore.ipsw
Version: b99eb81 - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket /Users/arinc/Desktop/odysseusOTA2/macos/shsh/612068262897-iPad2,5-8.4.1.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as p105ap, iPad2,5
Extracting BuildManifest from IPSW
Product Version: 8.4.1
Product Build: 12H321 Major: 12
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting iBSS.p105.RELEASE.dfu...
libc++abi.dylib: terminating with uncaught exception of type libipatcher::exception: std::exception
Abort trap: 6

**Comment by dvscru** [comment]
Go here 

https://www.reddit.com/r/jailbreak/comments/7sd9qb/tutorialhow_to_fix_libcabidylib_terminating_with/

Run the HTTP server from your home folder

**Comment by arinc9** [comment]
And just fucking 3 upvotes?! People on Reddit should care bout people who write tutorials. Thanks for helping. Gonna try this soon.

**Comment by dvscru** [comment]
@arinc9 I spent about 16 hours messing around with it. I finally decided to try that even though my error was slightly different.  Glad I did. Good luck.

**Comment by 0neday** [comment]
@dvscru I can find keys in [here](https://firmware-keys.ipsw.me/firmware/iPhone4,1/12B466).
but still get same error

Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 8.1.3
Product Build: 12B466 Major: 12
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting iBSS.n94.RELEASE.dfu...
libc++abi.dylib: terminating with uncaught exception of type libipatcher::exception: std::exception
Abort trap: 6

**Comment by dvscru** [comment]
@0neday You're running the webserver from your home directory?  If you http://localhost do you see the file you are hosting with the keys?

**Comment by 0neday** [comment]
yeah, use python web module

发自我的 iPhone

**Comment by 0neday** [comment]
@dvscru get new [error](https://github.com/tihmstar/futurerestore/issues/259)
